# Generated by Django 4.1.7 on 2023-04-03 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicado',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 22, 59, 51, 788310)),
        ),
    ]
